(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("boolean_form" . ("logic.info" 11591 541 "Definitions for logic"))
("characteristic_vector" . ("logic.info" 3037 1297 "Definitions for logic"))
("closed_under_f" . ("logic.info" 6414 397 "Definitions for logic"))
("closed_under_t" . ("logic.info" 6812 394 "Definitions for logic"))
("demorgan" . ("logic.info" 12133 380 "Definitions for logic"))
("dual_function" . ("logic.info" 5617 353 "Definitions for logic"))
("functionally_complete" . ("logic.info" 8944 626 "Definitions for logic"))
("linear" . ("logic.info" 8340 603 "Definitions for logic"))
("logic_basis" . ("logic.info" 9571 1437 "Definitions for logic"))
("logic_diff" . ("logic.info" 11009 581 "Definitions for logic"))
("logic_equiv" . ("logic.info" 4885 731 "Definitions for logic"))
("logic_simp" . ("logic.info" 2375 661 "Definitions for logic"))
("monotonic" . ("logic.info" 7207 1132 "Definitions for logic"))
("pcnf" . ("logic.info" 12762 226 "Definitions for logic"))
("pdnf" . ("logic.info" 12514 247 "Definitions for logic"))
("self_dual" . ("logic.info" 5971 442 "Definitions for logic"))
("zhegalkin_form" . ("logic.info" 4335 549 "Definitions for logic"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for logic" . ("logic.info" 2323 10665))
("Introduction to logic" . ("logic.info" 385 1812))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
