/* setup */
kill(all);
reset ();
sanitize (s) := ssubst ("", ")", ssubst ("", "(", ssubst ("_", " ", s)));
set_random_state (make_random_state (true)) $
myfile : sconcat (maxima_tempdir, "/maxima-", sanitize (build_info()@lisp_name), "-", 1000 + random (9000), ".log");
/* begin writefile */
writefile (myfile);
/* 2d output */
foo : expand ((x - y)^5) / expand ((a - b)^7);
/* describe */
?? write
1
/* different forms of printing */
grind (foo);
print ("print: foo = ", foo);
printf (true, "printf: foo = ~a~%", foo);
/* 1d output */
display2d : false;
foo;
/* end writefile */
closefile ();
reset (display2d);
print ("A message which shouldn't appear in the log file.");
/* begin appendfile */
appendfile (myfile);
/* 2d output */
foo : expand ((x - y)^5) / expand ((a - b)^7);
/* describe */
?? write
1
/* different forms of printing */
grind (foo);
print ("print: foo = ", foo);
printf (true, "printf: foo = ~a~%", foo);
/* 1d output */
display2d : false;
foo;
/* end appendfile */
closefile ();
print ("Another non-logged message.");
