/* test encoding CP1252 with batchload and batch */
(mystream: openr (file_search ("foo-CP1252.mac"), "CP1252"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-CP1252.mac"), "CP1252"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-CP1252.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-CP1252.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-1 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-1.mac"), "ISO-8859-1"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-1.mac"), "ISO-8859-1"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-1.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-1.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-2 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-2.mac"), "ISO-8859-2"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-2.mac"), "ISO-8859-2"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-2.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-2.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/*
/* test encoding ISO-8859-3 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-3.mac"), "ISO-8859-3"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-3.mac"), "ISO-8859-3"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-3.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-3.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-4 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-4.mac"), "ISO-8859-4"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-4.mac"), "ISO-8859-4"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-4.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-4.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-5 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-5.mac"), "ISO-8859-5"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-5.mac"), "ISO-8859-5"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-5.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-5.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-6 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-6.mac"), "ISO-8859-6"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-6.mac"), "ISO-8859-6"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-6.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-6.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-7 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-7.mac"), "ISO-8859-7"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-7.mac"), "ISO-8859-7"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-7.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-7.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-8 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-8.mac"), "ISO-8859-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-8.mac"), "ISO-8859-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-8.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-8.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-9 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-9.mac"), "ISO-8859-9"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-9.mac"), "ISO-8859-9"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-9.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-9.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-10 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-10.mac"), "ISO-8859-10"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-10.mac"), "ISO-8859-10"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-10.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-10.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-14 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-14.mac"), "ISO-8859-14"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-14.mac"), "ISO-8859-14"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-14.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-14.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;

/* test encoding ISO-8859-15 with batchload and batch */
(mystream: openr (file_search ("foo-ISO-8859-15.mac"), "ISO-8859-15"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-15.mac"), "ISO-8859-15"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-15.UTF-8.mac"), "UTF-8"), 0);
0;
(batchload (mystream), close (mystream), print (foo_string), 0);
0;
(mystream: openr (file_search ("foo-ISO-8859-15.UTF-8.mac"), "UTF-8"), 0);
0;
(batch (mystream), close (mystream), 0);
0;
 */
