name: Check
on: [ push, pull_request ]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: apt install gcl texinfo automake debhelper autoconf gawk texlive-latex-recommended sharutils python3
    - name: Check
      run: dpkg-buildpackage -B
