name: Check
on: [ push, pull_request ]
jobs:
  check:
    runs-on: ${{ matrix.os }}
    # push: always run.
    # pull_request: run only when the PR is submitted from a forked repository, not within this repository.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        os:
        #- ubuntu-latest
        - ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: "sudo apt update && sudo apt install sbcl cl-quicklisp debhelper texlive-latex-recommended sharutils libgmp3-dev libxmu-dev libxaw7-dev"
    - name: Install QuickLisp
      run: sudo sbcl --load /usr/share/common-lisp/source/quicklisp/quicklisp.lisp
    - name: Check
      run: dpkg-buildpackage -B
